---
version: '3'
services:
  master:
    build: ../..
    container_name: master
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./workspace:/opt/jenkins/data/workspace
    privileged: true

networks: {default: {}}  
